FROM almalinux:9
RUN dnf install nginx -y
RUN rm -rf /usr/share/nginx/html/index.html
## copy and ADD both copy the files from local but ADD has two more advantages 
## 1.it will directly copy the code from internet
## 2. it will untar or unzip the files into container
ADD https://raw.githubusercontent.com/daws-84s/notes/refs/heads/main/session-01.txt  /usr/share/nginx/html/index.html
RUN chmod +r /usr/share/nginx/html/index.html
ADD sample-1.tar /tmp/
CMD ["nginx", "-g" ,"daemon off;"]