FROM run:v1
RUN dnf install nginx -y 
RUN echo "vinodh"
##  CMD command will execute the at the  time of container creation 
## There should be single CMD instrcution inside the docker file if you give multiple it will take last one


CMD ["nginx","-g","daemon off;"]